name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Default Build
      run: cargo build
    - name: Run all tests
      run: cargo test --all-features
    - name: Compile example monitor
      run: cargo b --example monitor --features="poll"
    - name: Compile example pass
      run: cargo b --example pass
    - name: Compile example switch_power
      run: cargo b --example switch_power
